repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]  # auto-fix issues where possible

  - repo: local
    hooks:
      - id: run-pytest
        name: Run unit tests
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false  # prevent passing files as args
        working_directory: .   # run from repo root
