name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.1.2"

      - name: Install dependencies
        run: poetry install

      - name: Run ruff
        uses: astral-sh/ruff-action@v3

      - name: Run black check
        run: poetry run black --check .

      - name: Run tests
        run: poetry run pytest